name: Dev Environment CI

on:
  pull_request:
    paths:
      - 'infrastructure/envs/dev/**'
  push:
    paths:
      - 'infrastructure/envs/dev/**'
  workflow_dispatch:

jobs:
  call-dev-ci:
    uses: ./.github/workflows/ci-template.yaml
    with:
      env_name: dev
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
