name: Prod Environment CI

on:
  pull_request:
    paths:
      - 'infrastructure/envs/prod/**'

  workflow_dispatch:

jobs:
  call-prod-ci:
    uses: ./ci-template.yml
    with:
      env_name: prod
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
