name: Prod Environment CI

on:
  pull_request:
    paths:
      - 'infrastructure/envs/prod/**'
  push:
    paths:
      - 'infrastructure/envs/prod/**'
  workflow_dispatch:

jobs:
  call-prod-ci:
    uses: ./.github/workflows/ci-template.yaml
    with:
      env_name: prod
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
