name: CI for stage Environment

on:
  pull_request:
    paths:
      - 'infrastructure/envs/stage/**'

jobs:

  # -----------------------------------
  # STAGE 1: Format and Lint Checks
  # -----------------------------------
  lint:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      LOCALSTACK_HOST: http://localhost:4566

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.56.3

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive infrastructure/envs/stage

      - name: Check Terragrunt HCL formatting
        run: terragrunt hclfmt --check --recursive infrastructure/envs/stage

  # -----------------------------------
  # STAGE 2: Validate and Security Check
  # -----------------------------------
  validate:
    runs-on: ubuntu-latest
    needs: lint
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.56.3

      - name: Initialize with Terragrunt
        run: terragrunt init --working-dir infrastructure/envs/stage

      - name: Validate Terragrunt configuration
        run: terragrunt validate --working-dir infrastructure/envs/stage

      - name: Terragrunt Plan and Generate JSON
        run: |
          terragrunt plan \
            --all \
            --working-dir infrastructure/envs/stage \
            -out=tf.plan
          terraform show -json tf.plan > infrastructure/envs/stage/tf.json

      - name: Run Checkov static analysis
        run: checkov -f infrastructure/envs/stage/tf.json

      - name: Run custom policies (if present)
        run: |
          if [ -d custom_policies ]; then
            checkov -f infrastructure/envs/stage/tf.json --external-checks-dir custom_policies
          fi

      - name: Upload tf.json artifact for downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: tfjson-stage
          path: infrastructure/envs/stage/tf.json

  # -----------------------------------
  # STAGE 3: Infracost Analysis
  # -----------------------------------
  infracost:
    runs-on: ubuntu-latest
    needs: validate
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Download tf.json
        uses: actions/download-artifact@v4
        with:
          name: tfjson-stage
          path: tfjson

      - name: Run Infracost breakdown
        run: |
          infracost breakdown \
            --path=tfjson/tf.json \
            --usage-file=infracost/infracost-usage.yml \
            --format=github-comment \
            --show-skipped \
            --out-file=infracost-stage.json

      - name: Generate Infracost HTML report
        run: |
          infracost output \
            --path=infracost-stage.json \
            --format=html \
            --out-file=infracost-report-stage.html

      - name: Upload Infracost report artifact
        uses: actions/upload-artifact@v4
        with:
          name: infracost-report-stage
          path: infracost-report-stage.html
