name: Stage Environment CI

on:
  pull_request:
    paths:
      - 'infrastructure/envs/stage/**'

  workflow_dispatch:

jobs:
  call-stage-ci:
    uses: ./ci-template.yml
    with:
      env_name: stage
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
