# .github/workflows/ci-template.yml
name: Reusable CI for Terragrunt + Checkov + Infracost

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
    secrets:
      INFRACOST_API_KEY:
        required: true

jobs:
  terragrunt-ci:
    name: CI for ${{ inputs.env_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.81.7

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Install Checkov
        run: pip install checkov

      - name: Set plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV
          mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Run CI checks per module
        run: |
          CHECKOV_DIR="$GITHUB_WORKSPACE/checkov-reports"
          mkdir -p "$CHECKOV_DIR"

          for dir in infrastructure/envs/${{ inputs.env_name }}/*/; do
            echo "🔍 Module: $dir"
            cd "$dir"

            terragrunt init --parallelism=40
            terragrunt plan -out=tf.plan
            terragrunt show -json tf.plan > tf.json

            checkov --file tf.json --output json --soft-fail > checkov-report.json || true
            cp checkov-report.json "$CHECKOV_DIR/$(basename "$dir")-checkov.json"

            if [ -d "$GITHUB_WORKSPACE/custom_policies" ]; then
              checkov --skip-path tf.json --skip-check CKV* -d .terragrunt-cache --external-checks-dir "$GITHUB_WORKSPACE/custom_policies/terraform" --output json --soft-fail > custom-checkov-report.json || true
              cp custom-checkov-report.json "$CHECKOV_DIR/$(basename "$dir")-checkov-custom.json"
            fi

            cd - > /dev/null
          done

      - name: Run Infracost Breakdown
        run: |
          infracost breakdown \
            --path=infrastructure/envs/${{ inputs.env_name }} \
            --usage-file=infracost/infracost-usage.yml \
            --format=json \
            --out-file=infracost-${{ inputs.env_name }}.json

      - name: Generate Infracost HTML & Comment
        run: |
          infracost output --path=infracost-${{ inputs.env_name }}.json --format=html --out-file=infracost-report-${{ inputs.env_name }}.html
          infracost output --path=infracost-${{ inputs.env_name }}.json --format=github-comment --out-file=infracost-comment-${{ inputs.env_name }}.json

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ inputs.env_name }}
          path: |
            checkov-reports/
            infracost-report-${{ inputs.env_name }}.html
            infracost-comment-${{ inputs.env_name }}.json
