name: CI cache for Dev 2Environment

on:
  pull_request:
    paths:
      - 'infrastructure/envs/dev/**'

  workflow_dispatch:

jobs:
  dev-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.81.7

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Install Checkov & OPA
        run: |
          pip install checkov
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Set plugin cache environment variable
        run: echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV

      - name: Ensure plugin cache directory exists
        run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Check Terragrunt HCL formatting
        run: terragrunt hcl format

      - name: Validate Terragrunt configuration
        run: terragrunt hcl validate

     
      - name: Run Infracost breakdown
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          infracost breakdown \
            --config-file=infracost/infracost-config.yaml \
            --format=json \
            --out-file=infracost-dev.json

      - name: Evaluate Infracost Rego policies with OPA
        run: |
          echo "🔍 Evaluating Rego policies using OPA"
          for f in infracost/policies/**/*.rego; do
            echo "📜 Running policy: $f"
            opa eval --format=pretty \
              --data "$f" \
              --input infracost-dev.json \
              "data.infracost.deny"
          done


      - name: Fail if any Infracost policy fails
        run: |
          echo "🔍 Checking for violations..."
          FAILED=0
          for f in infracost/policies/**/*.rego; do
            echo "⏳ Evaluating $f..."
            result=$(opa eval --format=json --data "$f" --input infracost-dev.json "data.infracost.deny" | jq '.[0].expressions[0].value | length > 0')
            if [ "$result" == "true" ]; then
              echo "❌ Policy violation detected in $f"
              FAILED=1
            fi
          done
          exit $FAILED

      - name: Generate Infracost HTML report
        run: |
          infracost output \
            --path=infracost-dev.json \
            --format=html \
            --out-file=infracost-report-dev.html

      - name: Generate Infracost GitHub comment JSON (Optional for future)
        run: |
          infracost output \
            --path=infracost-dev.json \
            --format=github-comment \
            --out-file=infracost-comment.json

      - name: Upload Infracost reports
        uses: actions/upload-artifact@v4
        with:
          name: infracost-reports
          path: |
            infracost-report-dev.html
            infracost-comment.json

      - name: Upload Checkov reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-reports
          path: checkov-reports/

      - name: Debug Checkov Report Contents (Optional)
        if: always()
        run: |
          echo "📄 Listing Checkov reports:"
          ls -R checkov-reports || echo "❌ No reports found"
