name: CI for prod

on:
  pull_request:
    paths:
      - 'infrastructure/envs/prod/**'

jobs:
  call-ci:
    uses: ./.github/workflows/env-ci.yml
    with:
      env_name: prod
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
