name: CI for stage

on:
  pull_request:
    paths:
      - 'infrastructure/envs/stage/**'

jobs:
  call-ci:
    uses: ./.github/workflows/env-ci.yml
    with:
      env_name: stage
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
